// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lca_wrapper
CharacterVector lca_wrapper(CharacterVector accessions, CharacterVector taxonomy_strings);
RcppExport SEXP _taxozack_lca_wrapper(SEXP accessionsSEXP, SEXP taxonomy_stringsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type accessions(accessionsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type taxonomy_strings(taxonomy_stringsSEXP);
    rcpp_result_gen = Rcpp::wrap(lca_wrapper(accessions, taxonomy_strings));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_taxozack_lca_wrapper", (DL_FUNC) &_taxozack_lca_wrapper, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_taxozack(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
