# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_taxozack_wrappers", use_symbols = TRUE, package_name = "taxozack")

#' @usage NULL
#' @useDynLib taxozack, .registration = TRUE
NULL

lca_wrapper <- function(accessions, taxonomy_strings) .Call(wrap__lca_wrapper, accessions, taxonomy_strings)


# nolint end
