# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib taxozack, .registration = TRUE
#' @importFrom Rcpp sourceCpp
lca_wrapper <- function(accessions, taxonomy_strings) {
    .Call('_taxozack_lca_wrapper', PACKAGE = 'taxozack', accessions, taxonomy_strings)
}

